const CONFIG = {
  titleWeb: "Thuydot",
  introTitle: "Thuydot no1",
  introDesc: `Thủy dốt no1`,
  btnIntro: "nhấn vòa đây để chứng minh mình k dốt",
  title: "Bạn có ngu ko",
  desc: "chắc là có cùng có thể là ko ",
  btnYes: "Ngu",
  btnNo: "Không ngu",
  question: "Trên thế giới hơn 7 tỉ người mà sao bạn lại dốt vậy",
  btnReply: "Chứng minh xong",
  reply: "Vì tôi lười học",
  mess: "Mình biết mà 🥰.",
  messDesc: "Tối nay nhớ học lại tiếng việt nhé.",
  btnAccept: "Okiiiii lun <3",
  messLink: "https://www.facebook.com/profile.php?id=100012622455423",
};
